set -g default-command /bin/zsh

set -g base-index 1
setw -g pane-base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client
# connected to the *session*, constrain window size to the maximum size of any
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Status bar configuration
set -g status-interval 60
set -g status-left-length 40



# Settings tmux for 256 colors
set -g default-terminal "screen-256color"

#todo: make separate macos config
set-option -g default-command "reattach-to-user-namespace -l zsh"
